### ISSUE TITLE
Old releases (e.g. 0.5.0) got removed from Helm repo

### ISSUE THREAD

**Issue by pathob** [atlassian-labs/data-center-helm-charts#171]
Hey guys,

we noticed that some of the old releases (e.g. 0.5.0) got removed from the index.yaml in the repository. I know this project is in a very early stage, but we are also trying to adapt your new charts as soon and as early as possible. Hence two questions: Is there any particular reason why this happened and should we expect this more often?

Thanks for your answers.

Patrick

**Comment by nanux** [comment]
Hi @pathob, this was a one-off action where we wanted to clean up our development versions from the charts index. The old versions contained missing functionality and potentially could cause problems for the users, so we decided to remove them from the repo.

We are not planning any future removal and since 0.6.0 you can consider the helm charts stable for installation. I would still recommend using the latest version if possible.

I hope this clarifies any confusion.
